name: audit_cicd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/audit.csproj
    - name: Build
      run: dotnet build ./src/audit.csproj --no-restore
    - name: Test
      run: dotnet test ./tests/audit.unitTests/audit.unitTests.csproj -c Debug -p:coverletOutput=${{ github.workspace }}/coverage/lcov.info -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:Exclude=\"\" 
    - name: Coverlet coverage test
      uses: b3b00/coverlet-action@1.1.7
      with:
        output: ${{ github.workspace }}/coverage/lcov.info
    - name: Coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ${{ github.workspace }}/coverage/lcov.info

